### ISSUE TITLE
/home/common/shadow/src/external/elf-loader/vdl-map.c:740, file_map_do, Unable to perform remapping

### ISSUE THREAD

**Issue by zhangyunyunyun** [shadow/shadow-plugin-tor#114] opened 2021-02-08 16:57 UTC
I'm a new user , I first install the shadow-plugin-tor,  
when I run the "The minimal example can be run as follows”
# the minimal configuration was already extracted above
cd shadowtor-minimal
# run the simulation
shadow shadow.config.xml > shadow.log

I get error as follows:
** Starting Shadow v1.13.2-676-gd2fc305e 2021-02-02--10:26:23 with GLib v2.56.4 and IGraph v0.7.1
** Stopping Shadow, returning code -1 (error)
common@common-System-Product-Name:~/shadow-plugin-tor/resource/shadowtor-minimal$ cat shadow.log | grep error
00:00:05.282966 [thread-0] 00:20:00.000000000 [warning] [client~11.0.0.8] [process.c:966] [_process_logReturnCode] main error code '1' for process 'client.tgen.1000'
00:00:05.287828 [thread-0] 00:20:00.000000000 [warning] [torclient~11.0.0.9] [process.c:966] [_process_logReturnCode] main error code '1' for process 'torclient.tgen.1002'
00:00:05.292296 [thread-0] 00:20:00.000000000 [warning] [torhiddenclient~11.0.0.10] [process.c:966] [_process_logReturnCode] main error code '1' for process 'torhiddenclient.tgen.1002'
00:00:05.296638 [thread-0] 00:20:00.000000000 [warning] [torbridgeclient~11.0.0.11] [process.c:966] [_process_logReturnCode] main error code '1' for process 'torbridgeclient.tgen.1002'

and when I run :
cd vanilla 
shadow -w 3 shadow.config.xml > shadow.log

I get error as follows:
** Starting Shadow v1.13.2-676-gd2fc305e 2021-02-02--10:26:23 with GLib v2.56.4 and IGraph v0.7.1
/home/common/shadow/src/external/elf-loader/vdl-map.c:740, file_map_do, Unable to perform remapping
段错误 (核心已转储)

I don't know why? can someone help me, thank you.

**Comment by robgjansen** [comment] 2021-02-26 21:31
Closing as duplicate of shadow/shadow#1088.

**Closed by robgjansen** 2021-02-26 21:31 UTC
