### ISSUE TITLE
Running Tor in Shadow faild

### ISSUE THREAD

**Issue by myt0722** [shadow/shadow-plugin-tor#54] opened 2018-06-25 12:35 UTC
1. The test was successful in the _shadow_ environment
` shadow shadow.config.xml > shadow.log
** Starting Shadow v1.13.0-2-g443fdc2 2018-06-18 (built 2018-06-25) with GLib v2.54.2 and IGraph v0.7.1
** Stopping Shadow, returning code 0 (success)
`
2. The test failed in the _shadow plugin-tor_ environment
`shadow shadow.config.xml > shadow.log
** Starting Shadow v1.13.0-2-g443fdc2 2018-06-18 (built 2018-06-25) with GLib v2.54.2 and IGraph v0.7.1

(shadow:116853): GLib-CRITICAL **: g_hash_table_foreach: assertion 'hash_table != NULL' failed
** Stopping Shadow, returning code 1 (error)
`
3. The failure log is as follows：
`00:00:00.000108 [thread-0] n/a [message] [n/a] [shd-logger.c:296] [_logger_logStartupMessage] logging system started at 2018-06-25 20:27:47
00:00:00.000159 [thread-0] n/a [message] [n/a] [shd-main.c:352] [_main_helper] Starting Shadow v1.13.0-2-g443fdc2 2018-06-18 (built 2018-06-25) with GLib v2.54.2 and IGraph v0.7.1
00:00:00.000784 [thread-0] n/a [message] [n/a] [shd-main.c:359] [_main_helper] For more information, visit https://shadow.github.io or https://github.com/shadow
00:00:00.000788 [thread-0] n/a [message] [n/a] [shd-main.c:360] [_main_helper] logging current startup arguments and environment
00:00:00.000859 [thread-0] n/a [message] [n/a] [shd-main.c:316] [_main_logEnvironment] arg: shadow
00:00:00.000863 [thread-0] n/a [message] [n/a] [shd-main.c:316] [_main_logEnvironment] arg: shadow.config.xml
00:00:00.000870 [thread-0] n/a [message] [n/a] [shd-main.c:370] [_main_helper] shadow will automatically adjust environment and relaunch
00:00:00.000871 [thread-0] n/a [message] [n/a] [shd-main.c:371] [_main_helper] loading shadow configuration file
00:00:00.001068 [thread-0] n/a [message] [n/a] [shd-main.c:394] [_main_helper] shadow configuration file loaded, parsed, and passed validation
00:00:00.001086 [thread-0] n/a [message] [n/a] [shd-main.c:406] [_main_helper] setting up LD_PRELOAD environment
00:00:00.001107 [thread-0] n/a [message] [n/a] [shd-main.c:594] [_main_helper] setting up LD_STATIC_TLS_EXTRA environment
00:00:00.003970 [thread-0] n/a [message] [n/a] [shd-main.c:151] [_main_computeLoadSize] we need 144 bytes of static TLS per load of namespace with library at path '/root/.shadow/lib/libshadow-plugin-tgen.so'
00:00:00.005866 [thread-0] n/a [message] [n/a] [shd-main.c:151] [_main_computeLoadSize] we need 144 bytes of static TLS per load of namespace with library at path '/root/.shadow/lib/libshadow-plugin-tor.so' and preload at path '/root/.shadow/lib/libshadow-preload-tor.so'
00:00:00.006371 [thread-0] n/a [message] [n/a] [shd-main.c:151] [_main_computeLoadSize] we need 144 bytes of static TLS per load of namespace with library at path '/root/.shadow/lib/libshadow-plugin-torctl.so'
00:00:00.007070 [thread-0] n/a [message] [n/a] [shd-main.c:151] [_main_computeLoadSize] we need 0 bytes of static TLS per load of namespace with library at path '/root/.shadow/lib/libshadow-interpose.so'
00:00:00.007083 [thread-0] n/a [message] [n/a] [shd-main.c:303] [_main_getStaticTLSValue] finished checking TLS size required for 10 hosts; used dlmopen for 3 namespaces and cache for 19 namespaces
00:00:00.007091 [thread-0] n/a [message] [n/a] [shd-main.c:601] [_main_helper] we need 3745 total bytes of static TLS storage
00:00:00.007105 [thread-0] n/a [message] [n/a] [shd-main.c:642] [_main_helper] environment was updated; shadow is relaunching now with new environment
00:00:00.007165 [thread-0] n/a [message] [n/a] [shd-logger.c:310] [_logger_logShutdownMessage] logging system stopped at 2018-06-25 20:27:47, run time was 00:00:00
00:00:00.000217 [thread-0] n/a [message] [n/a] [shd-logger.c:296] [_logger_logStartupMessage] logging system started at 2018-06-25 20:27:47
00:00:00.000239 [thread-0] n/a [message] [n/a] [shd-main.c:352] [_main_helper] Starting Shadow v1.13.0-2-g443fdc2 2018-06-18 (built 2018-06-25) with GLib v2.54.2 and IGraph v0.7.1
00:00:00.000255 [thread-0] n/a [message] [n/a] [shd-main.c:359] [_main_helper] For more information, visit https://shadow.github.io or https://github.com/shadow
00:00:00.000257 [thread-0] n/a [message] [n/a] [shd-main.c:360] [_main_helper] logging current startup arguments and environment
00:00:00.000265 [thread-0] n/a [message] [n/a] [shd-main.c:316] [_main_logEnvironment] arg: shadow
00:00:00.000266 [thread-0] n/a [message] [n/a] [shd-main.c:316] [_main_logEnvironment] arg: shadow.config.xml
00:00:00.000267 [thread-0] n/a [message] [n/a] [shd-main.c:316] [_main_logEnvironment] arg: --preload=/root/.shadow/lib/libshadow-interpose.so
00:00:00.000272 [thread-0] n/a [message] [n/a] [shd-main.c:328] [_main_logEnvironment] env: LD_STATIC_TLS_EXTRA=3745
00:00:00.000273 [thread-0] n/a [message] [n/a] [shd-main.c:328] [_main_logEnvironment] env: SHADOW_SPAWNED=TRUE
00:00:00.000910 [thread-0] n/a [message] [n/a] [shd-main.c:696] [_main_helper] startup checks passed, we are ready to start simulation
00:00:00.000927 [thread-0] n/a [message] [n/a] [shd-master.c:92] [master_new] simulation master created
00:00:00.000931 [thread-0] n/a [message] [n/a] [shd-master.c:379] [master_run] loading and initializing simulation data
00:00:00.001097 [thread-0] n/a [message] [n/a] [shd-master.c:168] [_master_loadConfiguration] successfully parsed Shadow XML input!
00:00:00.001583 [thread-0] n/a [message] [n/a] [shd-topology.c:370] [_topology_loadGraph] reading graphml topology graph at '/tmp/shadow-topology-Y05ALZ.graphml.xml'...
00:00:00.001954 [thread-0] n/a [message] [n/a] [shd-topology.c:381] [_topology_loadGraph] successfully read graphml topology graph at '/tmp/shadow-topology-Y05ALZ.graphml.xml'
00:00:00.001971 [thread-0] n/a [message] [n/a] [shd-topology.c:713] [_topology_checkGraphProperties] checking graph properties...
00:00:00.002014 [thread-0] n/a [message] [n/a] [shd-topology.c:555] [_topology_checkGraphAttributes] checking graph attributes...
00:00:00.002037 [thread-0] n/a [warning] [n/a] [shd-topology.c:628] [_topology_checkGraphAttributes] vertex attribute 'geocode' has been renamed to 'countrycode' and is considered deprecated; please use 'countrycode' and/or 'citycode' instead
00:00:00.002047 [thread-0] n/a [message] [n/a] [shd-topology.c:701] [_topology_checkGraphAttributes] successfully verified all graph, vertex, and edge attributes
00:00:00.002073 [thread-0] n/a [message] [n/a] [shd-topology.c:788] [_topology_checkGraphProperties] topology graph is complete, undirected, and strongly connected with 1 cluster. It does not prefer direct paths.
00:00:00.002085 [thread-0] n/a [message] [n/a] [shd-topology.c:1004] [_topology_checkGraphVertices] checking graph vertices...
00:00:00.002103 [thread-0] n/a [warning] [n/a] [shd-topology.c:932] [_topology_checkGraphVerticesHelperHook] optional attribute 'asn' on vertex 0 (id='poi-1') is non-positive
00:00:00.002107 [thread-0] n/a [warning] [n/a] [shd-topology.c:996] [_topology_iterateAllVertices] we had a problem validating vertex attributes
00:00:00.002108 [thread-0] n/a [warning] [n/a] [shd-topology.c:1009] [_topology_checkGraphVertices] unable to validate graph vertices
00:00:00.002154 [thread-0] n/a [message] [n/a] [shd-topology.c:1262] [_topology_clearCache] path cache cleared, spent 0.000000 seconds computing 0 shortest paths with dijkstra, and 0.000000 seconds computing 0 shortest self paths
00:00:00.002180 [thread-0] n/a [critical] [n/a] [shd-topology.c:2485] [topology_new] we failed to create the simulation topology because we were unable to validate the topology graphml file
00:00:00.002225 [thread-0] n/a [critical] [n/a] [shd-master.c:213] [_master_loadTopology] fatal error loading topology at path '/tmp/shadow-topology-Y05ALZ.graphml.xml', check your syntax and try again
00:00:00.002251 [thread-0] n/a [message] [n/a] [shd-master.c:115] [master_free] simulation master destroyed
00:00:00.002253 [thread-0] n/a [message] [n/a] [shd-main.c:720] [_main_helper] Shadow v1.13.0-2-g443fdc2 2018-06-18 (built 2018-06-25) simulation was shut down cleanly, returning code 1
00:00:00.002305 [thread-0] n/a [message] [n/a] [shd-logger.c:310] [_logger_logShutdownMessage] logging system stopped at 2018-06-25 20:27:47, run time was 00:00:00`

so how could I do？

**Comment by robgjansen** [comment] 2018-06-25 18:35
Thanks for reporting this bug! The issue is that the `asn` attribute in the topology graphml file is no longer allowed to be non-positive as of shadow release 1.13.0.

I just pushed the latest changes that remove the asn attribute from the topology. Please try pulling in the latest changes from master, build, install, and then try again.

**Comment by myt0722** [comment] 2018-06-27 07:37
Thank you for your help! Now,There is a new problem with testing:
1.I have added the string CircuitPriorityHalflife 30 to the end of the *.torrc file located in the priority directory,so results are as follows
`[root@localhost priority]# shadow -w 3 shadow.config.xml > shadow.log** Starting Shadow v1.13.0-2-g443fdc2 2018-06-18 (built 2018-06-25) with GLib v2.54.2 and IGraph v0.7.1** Stopping Shadow, returning code 0 (success)`

2.In vanilla directory,the test failed.
`[root@localhost vanilla]# shadow -w 3 shadow.config.xml > shadow.log** Starting Shadow v1.13.0-2-g443fdc2 2018-06-18 (built 2018-06-25) with GLib v2.54.2 and IGraph v0.7.1  Killed`

**Comment by myt0722** [comment] 2018-06-27 07:38
Thank you for your help! Now,There is a new problem with testing:
1.I have added the string CircuitPriorityHalflife 30 to the end of the *.torrc file located in the priority directory,so results are as follows
`[root@localhost priority]# shadow -w 3 shadow.config.xml > shadow.log** Starting Shadow v1.13.0-2-g443fdc2 2018-06-18 (built 2018-06-25) with GLib v2.54.2 and IGraph v0.7.1** Stopping Shadow, returning code 0 (success)`

2.In vanilla directory,the test failed.What is _Killed_ reason？
`[root@localhost vanilla]# shadow -w 3 shadow.config.xml > shadow.log** Starting Shadow v1.13.0-2-g443fdc2 2018-06-18 (built 2018-06-25) with GLib v2.54.2 and IGraph v0.7.1  
Killed`

**Comment by robgjansen** [comment] 2018-06-27 19:57
Usually I've only seen Shadow killed when it uses too much RAM, and the operating system chooses to kill the process. Did that happen in your case?

**Comment by robgjansen** [comment] 2018-10-16 14:00
I assume this issue has been resolved and am closing due to non-response. Please re-open if you still need help.

**Closed by robgjansen** 2018-10-16 14:00 UTC
