### ISSUE TITLE
Generating topologies with old consensuses and descriptors

### ISSUE THREAD

**Issue by frochet** [shadow/shadow-plugin-tor#26] opened 2016-05-29 10:24 UTC
Hello,

I noticed something wrong when generating topologies with old consensuses and old descriptors. Here's the topology I have generated: python ../tools/generate.py --nauths 3 --nrelays 300 --nclients 1125 --nservers 130 --nperf50k 75 --nperf1m 75 --nperf5m 75 ../alexa-top-1000-ips.csv ../descriptors/consensuses-2015-05/25/2015-05-25-10-00-00-consensus ../descriptors/server-descriptors-2015-05/ ../descriptors/extra-infos-2015-05 ../descriptors/clients.csv
So, I'm using historical data from May 2015. The generate script itself goes well but the simulation goes wrong (using a Tor 0.2.6.7 binary). I noticed in the log of directory authorities the following lines:

Jan 01 00:49:41.000 [warn] Consensus with empty bandwidth: G=0 M=0 E=0 D=0 T=0

It seems like something goes wrong when applying measured bandwidths from the v3bw file. The consensus files have then the following lines:

"w Bandwidth=0 Unmeasured=1" for every routers in every consensuses and the bandwidth-weights value are set to 0:

bandwidth-weights Wbd=0 Wbe=0 Wbg=0 Wbm=10000 Wdb=10000 Web=10000 Wed=0 Wee=0 Weg=0 Wem=0 Wgb=10000 Wgd=0 Wgg=0 Wgm=0 Wmb=10000 Wmd=0 Wme=0 Wmg=0 Wmm=10000

This issue does not make shadow crashing but makes Tor clients selecting uniformly at random their nodes from each set (guard, middle, exit) to construct paths in the simulation.

Fix: [edit: wrong assumption]

**Comment by robgjansen** [comment] 2016-06-01 20:50
The problem you notice is already reported/explained in #21. The generate script already uses the work-around, but the work-around was only merged in Tor-0.2.7 stable. You version of Tor is too old and does not contain the fix.

The easiest way for you to fix this is to change your Tor as shown here:
https://trac.torproject.org/projects/tor/attachment/ticket/14881/0001-initialize-bw-to-1-in-testing-networks-when-producin.patch

I'm going to close this now as a duplicate of #21.

**Closed by robgjansen** 2016-06-01 20:50 UTC
Labels: duplicate

**Comment by frochet** [comment] 2016-06-02 06:57
Ow ! Did not see. Thanks :-)
