### ISSUE TITLE
[process_emu_pthread_mutexattr_settype] pthread_mutexattr_settype() is not supported by pth or by shadow

### ISSUE THREAD

**Issue by l2me-acc** [shadow/shadow-plugin-tor#37] opened 2017-06-23 12:26 UTC
i followed the install guides for shadow and shadow-plugin-tor, until i got to the section where i test with the minimal example from shadowtor-minimal-config.tar.xz.

to start the tor-shadow i use the following line:
`shadow-tor -i /home/${USER}/shadow/shadow-plugin-tor/resource/shadowtor-minimal/shadow.config.xml --preload=/home/spr/.shadow/lib/libshadow-interpose.so`

Btw, without the additional `--preload` at the end i get `** Environment Check Failed: LD_PRELOAD does not contain an absolute path to libshadow-interpose.so`, but that's not my problem

The plugin starts, but hangs after printing a few debug lines and in the log file quite immediately the following lines can be seen at the bottom:

```
00:00:00.144570 [thread-0] 00:01:00.000000000 [shadow-message] [bridge~100.0.0.1] [shd-process.c:643] [process_start] starting 'tor-1000' process and pth threading system
00:00:00.144862 [thread-0] 00:01:00.000000000 [shadow-message] [bridge~100.0.0.1] [shd-process.c:576] [_process_executeMain] calling main() for 'tor-1000' process
00:00:00.144922 [thread-0] 00:01:00.000000000 [shadow-warning] [bridge~100.0.0.1] [shd-process.c:5258] [process_emu_pthread_mutexattr_settype] pthread_mutexattr_settype() is not supported by pth or by shadow
00:00:00.226211 [thread-0] 00:01:00.000000000 [shadow-warning] [bridge~100.0.0.1] [shd-process.c:3879] [process_emu___cxa_atexit] atexit at library close is not currently supported
00:00:00.226327 [thread-0] 00:01:00.000000000 [shadow-warning] [bridge~100.0.0.1] [shd-process.c:548] [_process_logReturnCode] main error code '-1' for process 'tor-1000'
00:00:00.226358 [thread-0] 00:01:00.000000000 [shadow-message] [bridge~100.0.0.1] [shd-process.c:467] [_process_executeCleanup] cleaning up 'tor-1000' process: aborting 0 auxiliary threads and calling 0 atexit functions
00:00:00.226430 [thread-0] 00:01:00.000000000 [shadow-warning] [bridge~100.0.0.1] [shd-process.c:548] [_process_logReturnCode] main error code '-1' for process 'tor-1000'
00:00:00.226462 [thread-0] 00:01:00.000000000 [shadow-message] [relay1~11.0.0.5] [shd-process.c:643] [process_start] starting 'tor-1000' process and pth threading system
00:00:00.226679 [thread-0] 00:01:00.000000000 [shadow-message] [relay1~11.0.0.5] [shd-process.c:576] [_process_executeMain] calling main() for 'tor-1000' process
00:00:00.226734 [thread-0] 00:01:00.000000000 [shadow-warning] [relay1~11.0.0.5] [shd-process.c:5258] [process_emu_pthread_mutexattr_settype] pthread_mutexattr_settype() is not supported by pth or by shadow
00:00:00.308248 [thread-0] 00:01:00.000000000 [shadow-warning] [relay1~11.0.0.5] [shd-process.c:3879] [process_emu___cxa_atexit] atexit at library close is not currently supported
00:00:00.308358 [thread-0] 00:01:00.000000000 [shadow-warning] [relay1~11.0.0.5] [shd-process.c:548] [_process_logReturnCode] main error code '-1' for process 'tor-1000'
00:00:00.308389 [thread-0] 00:01:00.000000000 [shadow-message] [relay1~11.0.0.5] [shd-process.c:467] [_process_executeCleanup] cleaning up 'tor-1000' process: aborting 0 auxiliary threads and calling 0 atexit functions
00:00:00.308456 [thread-0] 00:01:00.000000000 [shadow-warning] [relay1~11.0.0.5] [shd-process.c:548] [_process_logReturnCode] main error code '-1' for process 'tor-1000'
```
Any way i can fix this?

**Comment by robgjansen** [comment] 2017-06-25 18:44
Are you using the master branch of both shadow and shadow-plugin-tor? I think that should work. You could also try falling back to the tagged shadow 1.11.2 release.

Which OS are you using and which version? I would like to try to reproduce the problem.

**Comment by l2me-acc** [comment] 2017-06-26 10:02
both master branches.
I'm using Debian 9 (Stretch), I'll try to purge the .shadow directory and re-try installing the tagged releases.
Btw, for reproducing, Deb9 requires slightly different packages than listed n the tutorial, but it's possible to find the right ones from the configure output.

**Comment by l2me-acc** [comment] 2017-06-26 15:44
I tested again. After removing everything and starting from scratch, the testnet works fine now. I think the difference is that this time I used the quick setup of plugin-tor, not the manual build way.

**Comment by robgjansen** [comment] 2017-06-26 15:47
OK great! I'm closing this now; please re-open if you have this problem again.

**Closed by robgjansen** 2017-06-26 15:47 UTC

**Comment by beastsam** [comment] 2019-03-21 09:03
@robgjansen  hi, i met the same problem too, can you help me to find out how to fix it?
 system is CentOS Linux release 7.5.1804
when i ran  `shadow shadow.config.xml > shadow.log` ,
![2019-03-21 15-49-44屏幕截图](https://user-images.githubusercontent.com/41358375/54739311-95dd7c00-4bf2-11e9-9046-fd0d5026e3bc.png)
as you can see, the program Core Dump. but my max_map count is ok?
later, i check my log file, i found some warnings without errors.
[shadow.log](https://github.com/shadow/shadow-plugin-tor/files/2991264/shadow.log)
the warnings such as
![image](https://user-images.githubusercontent.com/41358375/54740619-eb1b8c80-4bf6-11e9-8cae-7f228e664a40.png)

![image](https://user-images.githubusercontent.com/41358375/54740896-a80de900-4bf7-11e9-8e59-5e565c018ad9.png)

![image](https://user-images.githubusercontent.com/41358375/54740986-e6a3a380-4bf7-11e9-895c-23307cd1ed46.png)

![image](https://user-images.githubusercontent.com/41358375/54742021-291aaf80-4bfb-11e9-8fa9-15c9a56ad2c0.png)

**Comment by jtracey** [comment] 2019-03-23 19:34
@beastsam You can see the error in the first screenshot: Shadow can't open the plugin file (libshadow-plugin-tor.so). Usually this is caused by a low max_map_count, but other things can cause it as well. Make sure that the file exists at that path, and that you have read permissions on it. If you're still having issues, file a new bug report, because this one looks unrelated to what you're seeing.

**Comment by beastsam** [comment] 2019-03-24 08:29
> @beastsam You can see the error in the first screenshot: Shadow can't open the plugin file (libshadow-plugin-tor.so). Usually this is caused by a low max_map_count, but other things can cause it as well. Make sure that the file exists at that path, and that you have read permissions on it. If you're still having issues, file a new bug report, because this one looks unrelated to what you're seeing.

thank you for you reply, i will try this later.
