### ISSUE TITLE
Misconfigured graphml scripts

### ISSUE THREAD

**Issue by jmartinhoj** [shadow/shadow-plugin-tor#107] opened 2020-05-07 14:39 UTC
With the new release of tgen (1.0.0), it won't accept the "type" attribute in the hosts' configuration graphml file. As so, I recommend you to update your configuration files in the resources/ folder.

**Comment by jmartinhoj** [comment] 2020-05-07 14:40
I solved the issue by downgrading to tgen 0.0.1.

**Comment by stevenengler** [comment] 2020-06-24 15:27
Duplicate of #100.

**Closed** 2021-02-27 17:19 UTC
